### ISSUE TITLE
How to reproduce the results on NQ

### ISSUE THREAD

**Issue by shunyuzh** [texttron/tevatron#10]
Hi, @luyug 

Thanks for your awesome work.
Is it possible to give more details to reproduce the results (84.3=MRR@5) on NQ in the paper, just like the detailed MS MARCO tutorial demo?

Looking forward to your reply.
Thanks.

**Comment by luyug** [comment]
I used both BM25 and mined negatives, aligning with the DPR setup. I don't have thorough experiments on whether it is better to include or not to include BM25 negatives.

**Comment by Dopaminezsy** [comment]
Hi, @luyug 
I find it hard to reproduce your results for NQ and TQA, and it is lower about 0.5-1.5 points than your reported. I wonder if it's possible to get your mined hard negatives of NQ and TQA? My mail is shunyuz@126.com

**Comment by luyug** [comment]
I'm currently a little bit busy, working on several paper/school work deadlines. Will get back to you in a few weeks.

**Comment by luyug** [comment]
@Dopaminezsy I am assuming you are using `tevatron` for DPR repro? I wonder if you have tried using the original DPR toolkit. We are triaging some issues with DPR on tevatron right now.

**Comment by Dopaminezsy** [comment]
Sorry to reply later. I am now following the original DPR toolkit rather than Tevatron. 

So were your results totally based on Tevatron? I have noticed your shared [results](https://github.com/texttron/tevatron/tree/main/examples/dpr) is already higher than original DPR toolkit.

**Comment by luyug** [comment]
This is unexpected. I intentionally used the DPR toolkit in the paper to make sure the results are comparable to previous works. Locally I have been seeing rather stable results with DPR. I mentioned tevatron because we were having some unexpected regressions there.

If you are using DPR, make sure you are running the **exact** same setup as in the original DPR instruction, including 8GPUs, 16 batch size per device, DDP training, etc..

**Comment by Dopaminezsy** [comment]
Thanks, I will check them. In addition, I think the code about how to mine hard-negatives will help, for potentially different details. Another is can you share the first round results with only BM25 negatives on NQ, which may also help :)

**Comment by tecmry** [comment]
hi, I found that the number of bm25 negative samples and hard negative samples provided in [nq-example](https://github.com/texttron/tevatron/tree/main/examples/coCondenser-nq) is different, is this reasonable?
