### ISSUE TITLE
How to get the title in msmarco-passage

### ISSUE THREAD

**Issue by BeastyZ** [texttron/tevatron#106]
Hi, @MXueguang 
According to the collection in [TREC 2019 Deep Learning Track Guidelines](https://microsoft.github.io/msmarco/TREC-Deep-Learning-2019), there is no 'title' in corpus. But I see the 'title' in your [Tevatron/msmarco-passage](https://huggingface.co/datasets/Tevatron/msmarco-passage?row=0). May I know how you get the title?

**Comment by MXueguang** [comment]
Hi @BeastyZ , we follow the rocketqa released code/data to create the Tevatron/msmarco-passage, which contains title augmentation.


btw, this paper https://arxiv.org/pdf/2304.12904.pdf have an analysis of with/ with out title

**Comment by BeastyZ** [comment]
Thank you for your timely help many times.
