### ISSUE TITLE
How can I obtain the Wiki-ss dataset?

### ISSUE THREAD

**Issue by wuzhi19931128** [texttron/tevatron#136]
How can I obtain the Wiki-ss dataset mentioned in the paper https://arxiv.org/pdf/2406.11251?

**Comment by MXueguang** [comment]
Hi @wuzhi19931128 thanks for your interest. I am uploading it to huggingface, should be ready today.

**Comment by MXueguang** [comment]
@wuzhi19931128 

the file is above the 300g limit of huggingface, so I current host it here https://storage.googleapis.com/tevatron-vision/wiki-ss-hf-data.tar

please download with this link via `wget` and then load the data with `datasets.load_from_disk`

**Comment by wuzhi19931128** [comment]
grateful！

**Comment by zxy1728** [comment]
could you please share the link again? I  seem to be unable to download it with that link
