### ISSUE TITLE
Wiki-SS dataset

### ISSUE THREAD

**Issue by gabrielilharco** [texttron/tevatron#138]
Thank you for your excellent work! I recently came across this paper https://arxiv.org/abs/2406.11251, and I was wondering about the Wiki-SS dataset release timeline. Do you have a rough sense of when it will be available?

Thanks!

**Comment by MXueguang** [comment]
Hi @gabrielilharco please see https://github.com/texttron/tevatron/issues/136 for the data for now.

code releasing would be ready in a week.
