### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by CuongNN218** [texttron/tevatron#19]
I'm trying to train my local checkpoint using vinai/phobert on hugging face hub but I got this problem.
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/26113323/143205508-e3082a06-4f86-471f-82f2-4bfecdcf5564.png">
How can I solved it?

**Comment by MXueguang** [comment]
Hi @CuongNN218 ,

try to remove this line and rebuild? 
https://github.com/texttron/tevatron/blob/8490819d6619ae61acf1542400b8ad7c5b1999e7/src/tevatron/driver/train.py#L111

**Comment by CuongNN218** [comment]
@MXueguang Hi something is not correct, right ? It means that I can not load local pretrained model ?

**Comment by MXueguang** [comment]
you can load the local pretrained model after removing that line. or set `model_path=None`.
The local pretrained model will be loaded already before this line 
This line here was for recovering a training state iirc, which is not needed.
The local pretrained model (in huggingface format) should already been loaded  in https://github.com/texttron/tevatron/blob/8490819d6619ae61acf1542400b8ad7c5b1999e7/src/tevatron/driver/train.py#L73

**Comment by luyug** [comment]
The current design is that general pre-trained models should be loaded from the hub.
