### ISSUE TITLE
Cannot reproduce MRR@10 of Luyu/co-condenser-marco-retriever

### ISSUE THREAD

**Issue by cklsoft** [texttron/tevatron#23]
Hi @luyug , 
   Thanks for your great job! 
   I've use the two stages training described in `examples/coCondenser-marco/README.md`, but the final model is only MRR@10 36.2, less than the model released (`Luyu/co-condenser-marco-retriever` 38.2).

step 1. 

python -u -m torch.distributed.launch --nproc_per_node=8 ../../src/tevatron/driver/train.py --output_dir ./retriever_model_s1  --model_name_or_path $CONDENSER_MODEL_NAME  --save_steps 20000  --train_dir ./marco/bert/train --fp16 --per_device_train_batch_size 8 --learning_rate 5e-6 --num_train_epochs 3 --dataloader_num_workers 2

After training, MRR@10 on dev is 34.5

step 2.

create hard negatives 

python $SCRIPT_DIR/build_train_hn.py --tokenizer_name bert-base-uncased --hn_file ../train_q2i_rank.txt --qrels qrels.train.tsv  --queries train.query.txt --collection corpus.tsv --depth 200 --save_to bert/train-hn

step 3.

CONDENSER_MODEL_NAME=Luyu/co-condenser-marco
python -u -m torch.distributed.launch --nproc_per_node=8  ../../src/tevatron/driver/train.py --output_dir ./retriever_model_s2  --model_name_or_path $CONDENSER_MODEL_NAME  --save_steps 20000  --train_dir ./marco/bert/train-hn --fp16 --per_device_train_batch_size 8 --learning_rate 3e-5 --num_train_epochs 53--dataloader_num_workers 2

Besides, should we need the `negatives_x_device` option when training a dual-encoder for MSMARCO.

**Comment by luyug** [comment]
I'd suggest first run training follow the suggested hyper parameters. In particular, you are using a larger batch size than what is used in the example. A large batch size would typically require you to adjust optimization setup.
