### ISSUE TITLE
Specific paper to cite?

### ISSUE THREAD

**Issue by eugene-yang** [texttron/tevatron#26]
Is there any paper that you recommend us to cite if we use Tevatron in a research paper?

**Comment by luyug** [comment]
Thanks for your interest in citing Tevatron! We are working on a preprint that will be available on arxiv this or next week.

**Comment by luyug** [comment]
Thanks again for your interest in Tevatron! The pre-print is finally on arxiv now!
```
@article{Gao2022TevatronAE,
  title={Tevatron: An Efficient and Flexible Toolkit for Dense Retrieval},
  author={Luyu Gao and Xueguang Ma and Jimmy J. Lin and Jamie Callan},
  journal={ArXiv},
  year={2022},
  volume={abs/2203.05765}
}
```
