### ISSUE TITLE
RAG Implementation

### ISSUE THREAD

**Issue by salrowili** [texttron/tevatron#31]
Hi,
Any plan to implement RAG? RAG already had TF code with hugging face library and it actually uses PyTorch lightning. RAG achieve its best performance with LARGE BART and trained for 100 epochs which indicates that a working code on TPU is much needed, especially it requires large indexing which may not available for regular researchers with GPU but TPUv3-8 VM has 96 CPU and 350 RAM but it does not have GPU.

**Comment by MXueguang** [comment]
We currently don't have a plan for implement reader stage. close the issue for now.
