### ISSUE TITLE
Missing UniCOIL encoding file

### ISSUE THREAD

**Issue by hugoabonizio** [texttron/tevatron#39]
Following UniCOIL instructions it seems like the `encode_unicoil.py` file is missing in the `examples/unicoil` folder. Am I missing something?

**Comment by MXueguang** [comment]
Hi @hugoabonizio, just fixed in this PR: https://github.com/texttron/tevatron/pull/37
pull latest code should work

**Comment by hugoabonizio** [comment]
@MXueguang thank you for your quick reply!
