### ISSUE TITLE
how to improve the results with uniCOIL

### ISSUE THREAD

**Issue by caiyinqiong** [texttron/tevatron#47]
Hi,
Thanks for the great work!

I run experiments with the `modeling' in tevatron (but the data loader is implemented by myself)  on msmarco-passage. For DenseModel, the result can achieve to be MRR@10: 0.31+. But for uniCOIL, the result is only abot MRR@10: 0.26+ (this is far from your result 0.328).

In fact, I noticed that the implementation of uniCOIL in tevatron is somewhat different from the paper (https://github.com/luyug/COIL).  By comparison, I also run experiments with the code in https://github.com/luyug/COIL (dim=1 and no_cls), and get the similar result as above. 

Can you provide some insight on how to improve this result. For example, is there any special operation on the data for uniCOIL? I also try to initialize the model with distilbert as the example shows, but get a worse result.

**Comment by caiyinqiong** [comment]
batch size=8, hard negatives=7, q_len=32, d_len=128,  one gpu.
The encoding/index/search pipeline is conducted as https://github.com/texttron/tevatron/tree/main/examples/unicoil.

**Comment by MXueguang** [comment]
seems everything matches... could you try using our data with your data loader? to see where the difference comes from

**Comment by caiyinqiong** [comment]
ok,  I will check my code again, thank you.

**Comment by MXueguang** [comment]
Hi @caiyinqiong,
Is this issue good to close?
