### ISSUE TITLE
why no index for Dense Retrieval models

### ISSUE THREAD

**Issue by lboesen** [texttron/tevatron#62]
Hi, 

I was just wandering why we are not creating indexes for dpr models? and using tevatron.faiss_retriever right after encoding the queries and corpus. 

Thansk

**Comment by MXueguang** [comment]
Hi @lboesen , for dense model, we are using brute-force search by default (FlatIP index of Faiss). The index is built after the corpus embedding loaded while doing search https://github.com/texttron/tevatron/blob/2f6ac044855fbeda3bb9e2092c4172885f3532c2/src/tevatron/faiss_retriever/retriever.py#L16

**Comment by lboesen** [comment]
okay I see. Is the index saved ?

**Comment by MXueguang** [comment]
no, currently we only kept the embeddings and load as FaissFlatIP index at search time
