### ISSUE TITLE
The way to reproduce the results in DPR table 2

### ISSUE THREAD

**Issue by pygongnlp** [texttron/tevatron#65]
I have a question about how to experiment with BM25 baseline and incorperate BM25 with DPR, to get the similar results with DPR table 2? 

Thanks a lot

**Comment by MXueguang** [comment]
Hi @pygongnlp,

This work was trying to do the reproduce of Table2
https://github.com/castorini/pyserini/blob/master/docs/experiments-dpr.md

**Comment by pygongnlp** [comment]
So Thanks !
