### ISSUE TITLE
self.dataset.map in processors won't be cached

### ISSUE THREAD

**Issue by ArvinZhuang** [texttron/tevatron#70]
When using the self-contained training and corpus dataset the pretokenize process will be executed every time with the suggested library versions (torch==1.10.1, faiss-cpu==1.7.2, transformers==4.15.0, datasets==1.17.0).

The problem is self.dataset.map in processor classes is not caching properly, this seems to be a known issue of transformers datasets: https://github.com/huggingface/datasets/issues/4506

A solution to this is to reinstall datasets with a downgraded dill package: `pip install datasets==1.17.0 "dill<0.3.5"`

It seems this issue has been fixed in a newer version of datasets as well.

**Comment by MXueguang** [comment]
> A solution to this is to reinstall datasets with a downgraded dill package: pip install datasets==1.17.0 "dill<0.3.5"
> It seems this issue has been fixed in a newer version of datasets as well.
