### ISSUE TITLE
how to replicate leaderboard number?

### ISSUE THREAD

**Issue by Narabzad** [texttron/tevatron#8]
Hi,

I was able to replicate the MRR@10 that you reported in the paper ( 0.38) but I was wondering what is the difference between the number that is reported on the leaderboard ( 0.44) vs 0.38?
How do I replicate that? is it on a different set?

**Comment by MXueguang** [comment]
sorry for the very late reply....
There is a further reranker stage after the retriever on Luyu's leaderboard submission. from 0.38 to 0.44.
