### ISSUE TITLE
How to reproduce co-condenser-marco？

### ISSUE THREAD

**Issue by caiyinqiong** [texttron/tevatron#81]
Hi,
Thank you for your great work!
I encounter some issues when I tried to reproduce the results of co-condenser-marco on MARCO passage. I have referred to the [tutorial](https://github.com/texttron/tevatron/tree/main/examples/coCondenser-marco), but still cannot solve it (the problem seems to be in the step of mining hard negatives).

First, I run Fine-tuning Stage 1 with
```
CUDA_VISIBLE_DEVICES=3 python -m tevatron.driver.train \
  --output_dir model_msmarco_s1 \
  --model_name_or_path ../data/co-condenser-marco \
  --save_steps 20000 \
  --train_dir ../data/msmarco-passage/train_dir \
  --data_cache_dir ../data/msmarco-passage-train-cache \
  --fp16 \
  --dataloader_num_workers 2 \
  --per_device_train_batch_size 8 \
  --train_n_passages 8 \
  --learning_rate 5e-6 \
  --q_max_len 16 \
  --p_max_len 128 \
  --num_train_epochs 3 \
  --logging_steps 500 \
```
, and get MRR@10=0.3596, R@1000=0.9771. (Your reported results are MRR@10=0.357, R@1000=0.978).

Then, I run the hard negative mining with random sampling 30 negatives from the top-200 retrieval results of `model_msmarco_s1` by modifying [scripts/hn_mining.py](https://github.com/texttron/tevatron/blob/main/scripts/hn_mining.py) (according to the parameters in [build_train_hn.py](https://github.com/texttron/tevatron/blob/main/examples/coCondenser-marco/build_train_hn.py)).

Second, I run Fine-tuning Stage 2 with
```
CUDA_VISIBLE_DEVICES=3 python -m tevatron.driver.train \
  --output_dir model_msmarco_s2 \
  --model_name_or_path ../data/co-condenser-marco \
  --save_steps 20000 \
  --train_dir ../data/msmarco-passage/tain_dir_hn_dr_cocondenser200 \
  --data_cache_dir ../data/msmarco-passage-tain_hn_dr_cocondenser200-cache \
  --fp16 \
  --dataloader_num_workers 2 \
  --per_device_train_batch_size 8 \
  --train_n_passages 8 \
  --learning_rate 5e-6 \
  --q_max_len 16 \
  --p_max_len 128 \
  --num_train_epochs 2 \
  --logging_steps 500 \
```
, and get MRR@10=0.3657, R@1000=0.9761. (Your reported results are MRR@10=0.382, R@1000=0.984).

There are several possible issues that I would like to confirm:
1. The training data for Fine-tuning Stage 2 only is hard negatives, having not been concatenated with BM25 negatives?
2. The initial parameters of Fine-tuning Stage 2 are from `co-condenser-marco`, not the checkpoint of `model_msmarco_s1`?
3. The setting of `per_device_train_batch_size`, `train_n_passages`, `learning_rate`, and `num_train_epochs` in Fine-tuning Stage 2 ?

Thank you in advance!

**Comment by MXueguang** [comment]
> The concatenate_datasets in [hn_mining.py](https://github.com/texttron/tevatron/blob/559cf0fab1691ca0e814ddef42b3288cc1d09a4b/scripts/hn_mining.py#L105) leads to double the number of training queries.

Yes.

> I noticed this https://github.com/texttron/tevatron/issues/80 mentions the parameter of --passage_field_separator

yeah...using '[SEP]' is more close to the original setting. My guess is `" "` as separator should be fine, but may need a slightly hyperpara tune on stage 2 as the setting / codebase slightly different from original work.
I'll take a look on this too and update doc accordingly.

**Comment by caiyinqiong** [comment]
OK, thank you for your time. Looking forward to your check and updates.

It seems that using `" "` performs poorly (MRR@10=0.3733, R@1000=0.9800 as mentioned above). I will run the stage 2 with `'[SEP]'` and inform you about the result. (BTW, please check this line of [code](https://github.com/texttron/tevatron/blob/559cf0fab1691ca0e814ddef42b3288cc1d09a4b/src/tevatron/datasets/preprocessor.py#L52) if using '[SEP]').

Thanks again~

**Comment by caiyinqiong** [comment]
Hi @MXueguang, I re-run the stage 2 using `'[SEP]'`, initialized from `co-condenser-marco`, on the concatenate_datasets (mined with the aboved stage 1 results of dev MRR@10=0.3596, R@1000=0.9771). The result is MRR@10=0.3691, R@1000=0.9783. It still cannot reproduce the reported results of stage 2, and worse than using `" "`.

Could you update the [tutorial](https://github.com/texttron/tevatron/tree/main/examples/coCondenser-marco), especially the code of [Build HN Train file](https://github.com/texttron/tevatron/tree/main/examples/coCondenser-marco#build-hn-train-file) step? 
The hn_minging.py I used is [here](https://drive.google.com/file/d/1DOcM2hYZmJLk3YTvAA3FqwMqTGRKTrWl/view?usp=sharing), and run the hard negative mining with
```
mkdir -p ../data/msmarco-passage/tain_dir_hn_dr_cocondensercat200
python -m tevatron.datasets.hn_mining \
--train_data_name ../data/msmarco-passage/train_dir/train.jsonl \
--corpus_data_name ../data/msmarco-passage/corpus_dir/corpus.jsonl \
--cache_dir  ../data/msmarco-passage-hn-cache \
--result_path retrieval_msmarco_ckpt${ckpt}/rank_train.txt.trec \
--sample 30 \
--top 200 \
--min_hn 1 \
--output ../data/msmarco-passage/tain_dir_hn_dr_cocondensercat200/train.jsonl \
```
, and the stage 2 is run with
```
CUDA_VISIBLE_DEVICES=3 python -m tevatron.driver.train \
  --output_dir model_msmarco \
  --model_name_or_path ../data/co-condenser-marco \
  --save_steps 20000 \
  --train_dir ../data/msmarco-passage/tain_dir_hn_dr_cocondensercat200 \
  --data_cache_dir ../data/msmarco-passage-tain_hn_dr_cocondensercat200-cache \
  --fp16 \
  --dataloader_num_workers 2 \
  --per_device_train_batch_size 8 \
  --train_n_passages 8 \
  --learning_rate 5e-6 \
  --q_max_len 16 \
  --p_max_len 128 \
  --num_train_epochs 2 \
  --logging_steps 500 \
  --passage_field_separator '[SEP]'
```
Could you provide some guidance to reproduce your results? Thank you~

**Comment by MXueguang** [comment]
Hi @caiyinqiong, I think I located the issue here.
there is some inconsistency with the original data process script.

The self-contained dataset in Tevatron, i.e. `Tevatron/msmarco-passage` should be identical to [get_data.sh](https://github.com/texttron/tevatron/blob/main/examples/coCondenser-marco/get_data.sh#L17). Which results in 400k queries in training set. around 100k queries that doesn't get positive passage hit in top-k results are filtered. (so some too hard query are filtered left out in stage 1).

However, in the original hard mining script, the query for stage2 [here](https://github.com/texttron/tevatron/tree/main/examples/coCondenser-marco#encode-1) are the original 500k queries. 
And all together, the training data for stage two are 400k + 500k. The ~100k harder queries are missed if directly using the queries in first stage train data to encode & mine hard negatives.

I'm verifying if it is the issue makes the difference. I'm currently running stage2 training, it still requires 12 hours to finish on my machine.

**Comment by MXueguang** [comment]
Hi @caiyinqiong, there supposed to be 225000 steps in total with 2 epoches on hn data, but my machine got out of space to save the last checkpoint. I evaluated the 200000 steps checkpoint, it gives me 0.3804 mrr@10.

**Comment by caiyinqiong** [comment]
OK, great. I will run that, and share the result with you. Thank you~

**Comment by caiyinqiong** [comment]
Hi @MXueguang, the result (using `" "`) is mrr@10=0.3800 and R@1000=0.9848. It is close to the results reported in the paper. The problem really lies in the ~100k missed queries.
If there's no problem, I'll close this issue. Thank you very much~
