### ISSUE TITLE
Question regarding coCondenser-marco fine-tuning

### ISSUE THREAD

**Issue by zhiqihuang** [texttron/tevatron#86]
Hi, 

Thanks for the codebase. 

I have a question about coCondenser-marco fine-tuning command [here](https://github.com/texttron/tevatron/tree/main/examples/coCondenser-marco#fine-tuning-stage-1)

For example: 
```
python -m tevatron.driver.train \  
  --output_dir ./retriever_model_s1 \  
  --model_name_or_path CONDENSER_MODEL_NAME \  
  --save_steps 20000 \  
  --train_dir ./marco/bert/train \
  --fp16 \  
  --per_device_train_batch_size 8 \  
  --learning_rate 5e-6 \  
  --num_train_epochs 3 \  
  --dataloader_num_workers 2
```

Is this (plus the command for Fine-tuning Stage 2) the right command to reproduce `Luyu/co-condenser-marco-retriever`?  

It seems that this command only uses a single GPU with batch size = 8. (on the other hand, fine-tuning commands in coCondenser-nq uses 4 GPU with larger batch size (32) and negatives_x_device.

**Comment by MXueguang** [comment]
yes, cocondenser-marco-retriever was originally trained on single GPU with batch size 8.

**Comment by zhiqihuang** [comment]
Thanks, I will close this issue. Is there a reason for not using more GPUs with a larger batch size?
