### ISSUE TITLE
Training with my own dataset without HF token

### ISSUE THREAD

**Issue by ntnq4** [texttron/tevatron#88]
Hello,
Thank you for your work.

I’m trying to train a SPLADE model on my own dataset with my own BERT model.
According to the issue #84, I am using:

 ``` 
CUDA_VISIBLE_DEVICES=0` python -m train_splade.py \
  ...
  --dataset_name Tevatron/msmarco-passage \    (this will use the data process script but not the msmarco data)
  --train_dir <path to the custom jsonl file>
  ...
``` 

But I have the following issue: 
``` 
huggingface_hub.utils._headers.LocalTokenNotFoundError: Token is required (`token=True`), but no token found. 
You need to provide a token or be logged in to Hugging Face with `huggingface-cli login` or `huggingface_hub.login`.
``` 

Unfortunately, as I'm using a proxy, I can't interact directly with Huggingface.
Is there a way to get around that?

**Comment by MXueguang** [comment]
Hi, sorry for late reply.
Are you able to directly download files from huggingface hub via wget? 
e.g. `wget https://huggingface.co/datasets/Tevatron/msmarco-passage/resolve/main/train.jsonl.gz`

**Comment by MXueguang** [comment]
is it convenient for you post a line of your training data example here?

**Comment by ntnq4** [comment]
Yes, I have a jsonl file that look like that : 

`{"query_id": "0", "query": "Combien de personnes travaillent au ministère des sports", "positive_passages": [{"docid": "0", "title": "Sport", "text": "Le Ministère de la Jeunesse et des Sports estime à 100 000 (58 % d'hommes pour 42 % de femmes) le nombre de salariés travaillant pour le secteur sportif en France pour quelque 20 000 employeurs."}], "negative_passages": [{"docid": "88", "title": "La République en marche", "text": "Un an après l'élection présidentielle, LREM réaffirme [...] cependant éloigné de la sémantique initiale du progressisme qui est associée à la gauche. Le terme fait écho à une autre valeur déjà revendiquée par le parti avant l'élection : le rejet du conservatisme,.  "}, {"docid": "65", "title": "Louis-Napoléon Bonaparte (1856-1879)", "text": "Il ne fréquente pas l'école publique. À l'âge de sept ans, on lui attribue comme précepteur Francis Monnier, professeur au collège Rollin. [...] Un autre professeur, Ernest Lavisse (qui deviendra plus tard l'un des responsables de l'université républicaine), est nommé précepteur adjoint."}]}`

I have 5 negative passages for each query even if I show here only two queries.

and I'm executing : 
 ``` 
CUDA_VISIBLE_DEVICES=0 python train_splade.py \
  --output_dir french_SPALDE \
  --model_name_or_path ../camembert-base \
  --save_steps 20000 \
  --dataset_name msmarco-passage.py \
  --train_dir train_file.jsonl \
  --fp16 \
  --per_device_train_batch_size 8 \
  --train_n_passages 6 \
  --learning_rate 1e-5 \
  --q_max_len 128 \
  --p_max_len 128 \
  --q_flops_loss_factor 0.01 \
  --p_flops_loss_factor 0.01 \
  --num_train_epochs 100 \
  --logging_steps 500 \
  --overwrite_output_dir
 ```
