### ISSUE TITLE
Issues running DPR using tevatron. 

### ISSUE THREAD

**Issue by spacemanidol** [texttron/tevatron#9]
I am trying to repro the DPR with NQ benchmark but I am hitting errors as following the readme leads to errors. Any idea whats up?

les.json.json -   Failed to read file '/home/spacemanidol/tevatron/nq/biencoder-nq-train.json' with error <class 'pyarrow.lib.ArrowInvalid'>: JSON parse error: Column() changed from object to array in row 0 
    for obj in iterable:
  File "/home/spacemanidol/.local/lib/python3.8/site-packages/datasets/packaged_modules/json/json.py", line 140, in _generate_tables
    f"Not able to read records in the JSON file at {file}. "
AttributeError: 'list' object has no attribute 'keys'

**Comment by MXueguang** [comment]
Hi, @spacemanidol 
For your reference, this upcoming PR may also help.
https://github.com/texttron/tevatron/blob/7a3a05914cbeb8158b2ab8fe4c5f9990e03ef834/examples/dpr/README.md#alternatives-train-dpr-with-our-self-contained-datasets
The preprocessing can be faster if using our datasets hosted in huggingface hub.
